name: stacked_animated_list
description: Create visually stunning animated stacked lists. Transform your static lists into engaging, swipable card views.
homepage: https://github.com/abdulrehmank7/stacked-animated-list
repository: https://github.com/abdulrehmank7/stacked-animated-list
issue_tracker: https://github.com/abdulrehmank7/stacked-animated-list/issues
screenshots:
  - description: 'This screenshot show the animated list in action.'
    path: animated_list_preview copy.png
  - description: 'This screenshot show the animated list in action.'
    path: screen-20240707-171341.gif

topics:
  - animation
  - list
  - stacked
  - animated
  - listview
version: 1.0.2

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dartdoc: ^6.3.0

# The following section is specific to Flutter packages.
flutter: